### ISSUE TITLE
Table on README is not readable

### ISSUE THREAD

**Issue by jeevanjoseph** [oracle-quickstart/oci-ods-orm#7]
The `README.md` on the root of the repo has a table that lists the resources that will be created. This make sthe readme pretty unreadable. Reformat ?

**Comment by lyudmil-pelov** [comment]
Indeed, I just realized it too. Let me see what we could do about it.

**Comment by lyudmil-pelov** [comment]
Hey Jeevan, I think we were able to address the issue now with #9 let me know what you think about it.

**Comment by johnpeach** [comment]
fix it with PR # 8
